Cut the cucumber: one hand fixed
Open the fridge: one hand seeking
Open drawer: one hand seeking
Take object out of fridge: one hand seeking
Take object out of drawer: one hand seeking
Peel cucumber: one hand fixed
Bring pot to location: fixed offset
Open bottle: one hand fixed
