Cut the cucumber: one hand support
Open the fridge: one hand task
Open drawer: one hand task
Take object out of fridge: one hand task
Take object out of drawer: one hand task
Peel cucumber: one hand support
Bring pot to location: fixed offset
Open bottle: one hand support
